### ISSUE TITLE
Cant use some Tailwind classes

### ISSUE THREAD

**Issue by fungayimakoni** [pixeldevsio/tailpress#2]
Hi, Im new to Tailwind css but I'm loving this theme its great since I was already used to underscores starter theme for all my projects. However for some reason I can't use some of the Tailwind classes. Not sure if its a me problem or theme related. Is there anything I can adjust to make all classes applicable. e.g all background image classes, w-1/3, flex-1 etc

**Comment by pixeldevsio** [comment]
Hey! Thanks for sending this feedback. I tested out the classes you mentioned and it seems to be working on my install. Can you post your code so I can see how you're adding it? also, can you include your tailwind.config.js so I can see if there's an issue with it?

![image](https://user-images.githubusercontent.com/59432382/121511657-dfbf0200-c9b6-11eb-9e96-c9d44c61aa96.png)

**Comment by fungayimakoni** [comment]
> Hey! Thanks for sending this feedback. I tested out the classes you mentioned and it seems to be working on my install. Can you post your code so I can see how you're adding it? also, can you include your tailwind.config.js so I can see if there's an issue with it?
> 
> ![image](https://user-images.githubusercontent.com/59432382/121511657-dfbf0200-c9b6-11eb-9e96-c9d44c61aa96.png)

Thanks for quick response. I have managed to fix the problem. The templates failing to read the mentioned classes are in tailpress/template-parts/articles/latest-articles.php for example

Then I looked into the tailwind.config.js under purge option
purge: {
        content: [
            './*.php',
            './*/*.php',
            './safelist.txt'
        ],
    },

Added an extra line with './*/*/*.php', to become
purge: {
        content: [
            './*.php',
            './*/*.php',
            './*/*/*.php',
            './safelist.txt'
        ],
    },

Now its working. all the Tailwind classes referenced from these template parts are showing.
I'm not sure if what I have added is a good practice. I would appreciate appreciate your advice.

**Comment by pixeldevsio** [comment]
Ah gotcha. Yeah I didn't include nested / nested folder structures as the initial theme isn't set up that way. Good call. Wanna submit a pull request and I'll merge it in?

**Comment by pixeldevsio** [comment]
As @fungayimakoni referenced above, if you want to have nested folder structures in your PHP, make sure to modify the PurgeCSS structure in **tailwind.config.js**

```purge: {
content: [
'./.php',
'.//.php',
'.///*.php',
'./safelist.txt'
],
},```
